ALTER DATABASE INTRANET_WEB SET SINGLE_USER WITH ROLLBACK IMMEDIATE

RESTORE DATABASE INTRANET_WEB
FROM DISK = 'B:\MSSQL10_50.MSSQLSERVER\MSSQL\Backup\SIP_WEB_Live\SIP_WEB_Live_backup_2015_06_22_210003_6733191.bak'
WITH STATS, REPLACE

ALTER DATABASE INTRANET_WEB SET MULTI_USER